apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: market-research
  labels:
    app: market-backend
spec:
  type: ClusterIP
  selector:
    app: market-backend
  ports:
  - name: http
    port: 8000
    targetPort: http
