apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: trading-journal

type: Opaque

stringData:
  POSTGRES_USER: "<secret>"
  POSTGRES_PASSWORD: "<secret>"
  POSTGRES_DB: "<secret>"