apiVersion: v1
kind: Service
metadata:
  name: market-strategy-lab-service
  namespace: market-research
  labels:
    app: market-strategy-lab-service
spec:
  type: ClusterIP
  selector:
    app: market-strategy-lab
  ports:
  - name: http
    port: 8080
    targetPort: http
