apiVersion: v1
kind: Service
metadata:
  name: internal-backend
  namespace: market-research
  labels:
    app: market-internal-backend
spec:
  type: ClusterIP
  selector:
    app: market-internal-backend
  ports:
  - name: http
    port: 8001
    targetPort: http
